#!/bin/bash

echo "================================================"
echo "CAREERS APPLICATION SETUP"
echo "================================================"
echo ""
echo "Step 1: Run SQL to create career_applications table"
echo "----------------------------------------------"
echo "Go to: https://supabase.com/dashboard/project/gakgjtaykpflknfmezez/sql/new"
echo ""
echo "Copy and paste the SQL from:"
echo "  supabase/career-applications-schema.sql"
echo ""
echo ""
echo "Step 2: Set Brevo Careers List ID Secret"
echo "----------------------------------------------"
echo "Run this command (replace YOUR_LIST_ID with actual Brevo list ID):"
echo ""
echo "supabase secrets set BREVO_CAREERS_LIST_ID=YOUR_LIST_ID --project-ref gakgjtaykpflknfmezez"
echo ""
echo "OR set it in Supabase Dashboard:"
echo "https://supabase.com/dashboard/project/gakgjtaykpflknfmezez/settings/functions"
echo ""
echo ""
echo "Step 3: Deploy the Edge Function"
echo "----------------------------------------------"
echo "The function 'submit-career-application' will be deployed automatically."
echo "It uses the same BREVO_API_KEY secret that's already configured."
echo ""
echo "================================================"
echo ""
echo "After setup, all career application buttons will:"
echo "  ✓ Open a modal form"
echo "  ✓ Save application to Supabase"
echo "  ✓ Create/update contact in Brevo"
echo "  ✓ Add to careers list (if user opts in)"
echo "  ✓ Send notification email to hello@orjumedia.com"
echo ""
echo "================================================"
